### ISSUE TITLE
RuntimeIOException: java.io.IOException: Unable to open "edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz" as class path, filename or URL

### ISSUE THREAD

**Issue by igrgurina** [yakivyusin/SimpleNetNlp#19]
I'm trying to do a simple Sentiment() on the pure Sentence with simple text as an API call in ASP.NET Core, but when running it, it keeps throwing this inner exception. I checked and the files seem to be there.

RuntimeIOException: java.io.IOException: Unable to open "edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz" as class path, filename or URL

**Comment by yakivyusin** [comment]
Hello!

Thank you for your interest in the SimpleNetNlp library.

Are you running your ASP.NET Core app from a Visual Studio debug session or a published app under a web server?

**Comment by igrgurina** [comment]
Debug session, and I can see the files are there.
I have all the files available, from what I can see:
![image](https://github.com/yakivyusin/SimpleNetNlp/assets/2978480/1c907c31-5801-4af9-b82a-d9fc3f2db068)

I have the class library and then the ASP.NET Core app that references it. I thought maybe that was the issue, so I stripped that, added it, and called the SimpleNetNlp directly from the ASP.NET Core app in the controller action - still the same issue, even though I can see the files.

**Comment by yakivyusin** [comment]
When you run a web application from Visual Studio, it sets the current working directory to the project folder, not bin/Debug/net7.0.
Because the model files are not physically placed in the project folder, but are only copied to bin/Debug/net7.0 when building (or to the publish directory when publishing), you get this error.
You can change this behavior of Visual Studio (and set the CWD to bin/Debug/net7.0) by manually modifying the launchSettings.json file or by using the Visual Studio GUI.

**Comment by yakivyusin** [comment]
Closed due to inactivity.
