### ISSUE TITLE
Issue with english-left3words-distsim.tagger after publishing

### ISSUE THREAD

**Issue by z01c** [yakivyusin/SimpleNetNlp#6]
SimpleNetNlp works perfect when I am running my project in Visual Studio. However, if I publish the project and run the installed application I run into this error -
"java.io.IOException: Unable to open "edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger" as class path, filename or URL"
Is there a known issue with this?

**Comment by yakivyusin** [comment]
Hi!

Yes, it's known problem (e.g. #3 ).
In short: when you run application from VS, folder with models are creating by MSBuild scripts that are contained in model packages. Unfortunalley, when you publish application these scripts aren't called. So, for publish application you must manually copy folder with models (`edu` in bin) in your target place or try to modificate .csproj as was mentioned in #2 .

**Comment by jdavid1385** [comment]
This issue also appears while running nUnit tests using the [VisualStudio Test Adapter]( https://github.com/nunit/docs/wiki/Visual-Studio-Test-Adapter). The _edu_ folder is in the executing assembly location (bin\edu\**).
To make it work I had to set the current working directory for all tests via `Directory.SetCurrentDirectory(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location))` . Now this is something I would love to understand, why this setting would affect the behavior of the test if the tests are running on the right location? i.e., `Assembly.GetExecutingAssembly().Location='bin'`

**Comment by keith5000** [comment]
This issue also happens when SimpleNetNlp is referenced in a class library. Any executables referencing the class library will also fail with this error, which is a huge showstopper in my case.

I tried manually adding the edu directory to the project and setting the files' Build Action and Copy settings to copy to the bin but this still doesn't fix the problem, which I can't understand why.

Any suggestions would be appreciated. For now it seems I'm going to have to use something else.

**Comment by yakivyusin** [comment]
closed by #11
